---
- name: Promote Windows Server to Domain Controller and Configure DNS
  hosts: dc
  vars:
    ansible_user: "Administrator"
    ansible_password: "passw0rd!"
    ansible_connection: winrm
    ansible_winrm_transport: ntlm
    ansible_winrm_server_cert_validation: ignore
    domain_name: "office.uk"
    new_hostname: "DC01"
    dns_ip: "14.0.1.1"
    safe_mode_password: "{{ ansible_password }}"
    dhcp_start_ip: "14.0.2.10"
    dhcp_end_ip: "14.0.2.100"
    dhcp_subnet_mask: "255.255.255.0"
    dhcp_default_gateway: "14.0.2.254"
    dhcp_scope_name: "Scope01"
    dhcp_scope_subnet: "14.0.2.0"
    dhcp_scope_description: "Main Office DHCP Scope"
    dhcp_script_path: "C:\\Configure-DHCP.ps1"
    mapdrive_script_path: "C:\\Configure-mapdrive.ps1"

  tasks:
    - name: Rename computer to DC01
      ansible.windows.win_hostname:
        name: "{{ new_hostname }}"
      register: rename_result

    - name: Reboot after hostname change (if needed)
      ansible.windows.win_reboot:
        reboot_timeout: 600
      when: rename_result.reboot_required

    - name: Install AD-Domain-Services feature
      ansible.windows.win_feature:
        name: AD-Domain-Services
        include_management_tools: yes
        state: present

    - name: Promote to Domain Controller and create new forest
      microsoft.ad.domain:
        dns_domain_name: "{{ domain_name }}"
        safe_mode_password: "{{ safe_mode_password }}"
        domain_netbios_name: "OFFICE"
        forest_mode: "Win2012R2"
        install_dns: yes
        sysvol_path: "C:\\Windows\\SYSVOL"
        database_path: "C:\\Windows\\NTDS"
        reboot: yes
        domain_mode: "Win2012R2"
      register: domain_promotion

    - name: Reboot after domain controller promotion
      ansible.windows.win_reboot:
        reboot_timeout: 600
      when: domain_promotion.reboot_required

    - name: Install DNS Server role
      ansible.windows.win_feature:
        name: DNS
        state: present

    - name: Add A and PTR records for office.uk
      ansible.windows.win_powershell:
        script: |
          $zoneName = "office.uk"
          $recordName = "office"
          $ipAddress = "14.0.1.1"
          Add-DnsServerResourceRecordA -Name $recordName -ZoneName $zoneName -IPv4Address $ipAddress
          Add-DnsServerResourceRecordPtr -Name $recordName -ZoneName "$ipAddress.in-addr.arpa" -PtrDomainName "$zoneName"

    - name: Write PowerShell DHCP configuration script to C drive
      ansible.windows.win_copy:
        dest: "{{ dhcp_script_path }}"
        content: |
          $DhcpStartIp = "{{ dhcp_start_ip }}"
          $DhcpEndIp = "{{ dhcp_end_ip }}"
          $DhcpSubnetMask = "{{ dhcp_subnet_mask }}"
          $DhcpDefaultGateway = "{{ dhcp_default_gateway }}"
          $ScopeName = "{{ dhcp_scope_name }}"
          $ScopeSubnet = "{{ dhcp_scope_subnet }}"
          $ScopeDescription = "{{ dhcp_scope_description }}"

          if (-not (Get-WindowsFeature -Name DHCP).Installed) {
              Install-WindowsFeature -Name 'DHCP' -IncludeManagementTools
          }

          if (-not (Get-DhcpServerv4Scope | Where-Object { $_.Name -eq $ScopeName })) {
              Add-DhcpServerv4Scope -Name $ScopeName `
                  -StartRange $DhcpStartIp `
                  -EndRange $DhcpEndIp `
                  -SubnetMask $DhcpSubnetMask `
                  -Description $ScopeDescription
          }

          $routerOption = Get-DhcpServerv4OptionValue -ScopeId $ScopeSubnet -OptionId 3 -ErrorAction SilentlyContinue
          if (-not $routerOption) {
              Set-DhcpServerv4OptionValue -ScopeId $ScopeSubnet -Router $DhcpDefaultGateway
          }

          $hostname = (Get-WmiObject Win32_ComputerSystem).Name
          $ipAddress = (Get-NetIPAddress -AddressFamily IPv4 | Where-Object {$_.InterfaceAlias -notlike "*Loopback*"} | Select-Object -First 1 -ExpandProperty IPAddress)
          $authorized = Get-DhcpServerInDC | Where-Object { $_.DnsName -eq $hostname }
          if (-not $authorized) {
              Add-DhcpServerInDC -DnsName $hostname -IpAddress $ipAddress
          }

    - name: Run DHCP setup PowerShell script
      ansible.windows.win_shell: powershell.exe -ExecutionPolicy Bypass -File "{{ dhcp_script_path }}"

    - name: Delete the PowerShell script after execution
      ansible.windows.win_file:
        path: "{{ dhcp_script_path }}"
        state: absent

    - name: Write PowerShell GPO mapping network drive script to C drive
      ansible.windows.win_copy:
        dest: "{{ mapdrive_script_path }}"
        content: |
          # Import the GroupPolicy module (if not already imported)
          Import-Module GroupPolicy

          # Set variables
          $gpoName = "Map X Drive"
          $driveLetter = "X:"
          $sharePath = "\\fs01\Threat Level Midnight"
          $domainDN = (Get-ADDomain).DistinguishedName

          # Create the GPO
          $gpo = New-GPO -Name $gpoName -ErrorAction Stop

          # Link the GPO to the domain so it applies to all users
          New-GPLink -Name $gpoName -Target "DC=$($domainDN -replace ',',',DC=')" -LinkEnabled Yes

          # Define the drive mapping XML
          $xml = @'
          <?xml version="1.0" encoding="utf-8"?>
          <DriveMaps clsid="{5794DAFD-BE60-433f-88A2-1A31939AC01F}">
            <DriveMap>
              <Properties action="U" thisDrive="X" userName="" path="\\fs01\Threat Level Midnight" label="Threat Level Midnight" 
                          reconnect="1" useLetter="1" hideRestore="0" 
                          letter="X" newDriveLetter="X" 
                          persistent="1" 
                          showAction="replace" />
              <Filters />
            </DriveMap>
          </DriveMaps>
          '@

                    # Convert XML to required file structure
                    $tempPath = "$env:TEMP\DriveMap.xml"
                    $xml | Out-File -Encoding UTF8 $tempPath

                    # Set the preference item in the GPO using LGPO COM interface
                    $gpoPath = "\\$env:USERDOMAIN\SysVol\$env:USERDOMAIN\Policies\{$($gpo.Id)}\User\Preferences\Drives"
                    New-Item -Path $gpoPath -ItemType Directory -Force
                    Copy-Item -Path $tempPath -Destination "$gpoPath\Drivemap.xml"


    - name: Run GPO mapping network drive PowerShell script
      ansible.windows.win_shell: powershell.exe -ExecutionPolicy Bypass -File "{{ mapdrive_script_path }}"

    - name: Delete the PowerShell script after execution
      ansible.windows.win_file:
        path: "{{ mapdrive_script_path }}"
        state: absent
