---
- name: Create GPO to map network drive Z to \\fs01\Internal and make it persistent
  hosts: fs
  vars:
    gpo_name: "MapInternalDrive"
    drive_letter: "Z:"
    share_path: "\\\\fs01\\Internal"
    domain: "warehouse.uk"
    script_path: "\\\\fs01\\Internal\\create-gpo-map-drive.ps1"

  tasks:
    - name: Create PowerShell script to create GPO and map the network drive
      ansible.windows.win_copy:
        content: |
          $gpoName = "Map Internal Share to Z:"
          $gpo = Get-GPO -Name $gpoName -ErrorAction SilentlyContinue
          if (-not $gpo) {
              $gpo = New-GPO -Name $gpoName
              Write-Host "GPO '$gpoName' created successfully."
          } else {
              Write-Host "GPO '$gpoName' already exists. Updating it."
          }

          # Configure the Drive Map under User Configuration
          $driveLetter = "Z:"
          $remotePath  = "\\\\fs01\\Internal"

          # Get the Drive Maps settings for the GPO
          $driveMapSettings = Get-GPRegistryValue -Name $gpoName -Key "Software\\Microsoft\\Windows\\CurrentVersion\\Policies\\Explorer\\NetworkDrives" -ErrorAction SilentlyContinue

          # Check if a setting for Z: already exists and remove it if so
          if ($driveMapSettings -ne $null) {
              $existingDrive = $driveMapSettings | Where-Object { $_.ValueName -eq $driveLetter }
              if ($existingDrive) {
                  Remove-GPRegistryValue -Name $gpoName -Key "Software\\Microsoft\\Windows\\CurrentVersion\\Policies\\Explorer\\NetworkDrives" -ValueName $driveLetter
                  Write-Host "Existing mapping for '$driveLetter' removed from GPO '$gpoName'."
              }
          }

          # Create the registry values to map the drive
          Set-GPRegistryValue -Name $gpoName -Key "Software\\Microsoft\\Windows\\CurrentVersion\\Policies\\Explorer\\NetworkDrives" -ValueName $driveLetter -Type String -Value $remotePath
          Set-GPRegistryValue -Name $gpoName -Key "Software\\Microsoft\\Windows\\CurrentVersion\\Policies\\Explorer\\NetworkDrives" -ValueName "ShowZ" -Type DWord -Value 1
          Set-GPRegistryValue -Name $gpoName -Key "Software\\Microsoft\\Windows\\CurrentVersion\\Policies\\Explorer\\NetworkDrives" -ValueName "UseCache" -Type DWord -Value 0

        dest: "{{ script_path }}"
        owner: SYSTEM
        group: SYSTEM
        mode: '0755'

- name: Run PowerShell script on DC to create GPO for drive mapping
  hosts: dc
  vars:
    script_path: "\\\\fs01\\Internal\\create-gpo-map-drive.ps1"

  tasks:
    - name: Run the PowerShell script to create GPO and map drive
      ansible.windows.win_powershell:
        script: "{{ script_path }}"
