---
- name: Add network bridges to Proxmox
  hosts: proxmox
  become: yes
  vars:
    api_host: "{{ proxmox_api_host }}"
    api_user: "{{ proxmox_api_user }}"
    api_token_id: "{{ proxmox_api_token_id }}"
    api_token_secret: "{{ proxmox_api_token_secret }}"
    proxmox_node: "{{ proxmox_node }}"

  tasks:
  #Server
    - name: Add vmbr30 block
      blockinfile:
        path: /etc/network/interfaces
        marker: "# {mark} ANSIBLE vmbr30"
        block: |
          auto vmbr30
          iface vmbr30 inet static
          address 14.0.1.0/24
          netmask 255.255.255.0
          bridge_ports none
  #WKS
    - name: Add vmbr31 block
      blockinfile:
        path: /etc/network/interfaces
        marker: "# {mark} ANSIBLE vmbr31"
        block: |
          auto vmbr31
          iface vmbr31 inet static
          address 14.0.2.0/24
          netmask 255.255.255.0
          bridge_ports none
  #DMZ INT
    - name: Add vmbr32 block
      blockinfile:
        path: /etc/network/interfaces
        marker: "# {mark} ANSIBLE vmbr32"
        block: |
          auto vmbr32
          iface vmbr32 inet static
          address 14.0.3.0/24
          netmask 255.255.255.0
          bridge_ports none
  #DMZ OUT
    - name: Add vmbr33 block
      blockinfile:
        path: /etc/network/interfaces
        marker: "# {mark} ANSIBLE vmbr33"
        block: |
          auto vmbr33
          iface vmbr33 inet static
          address 14.0.4.0/24
          netmask 255.255.255.0
          bridge_ports none

    - name: Restart networking on Proxmox
      systemd:
        name: networking
        state: restarted
